# Generated by Django 5.2.1 on 2025-05-29 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VrstaJela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(max_length=100, unique=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=10)),
                ('opis', models.TextField(blank=True, null=True)),
                ('slika', models.ImageField(blank=True, null=True, upload_to='jela/')),
                ('vrsta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jela', to='base.vrstajela')),
            ],
        ),
    ]
